"""Email digest via Gmail SMTP (App Password)."""

from __future__ import annotations

import logging
import re
import smtplib
import ssl
from email.message import EmailMessage
from html import escape

from ..models import Job

log = logging.getLogger(__name__)

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465

_CATEGORY_LABELS = {
    "software": "💻 Software Engineering",
    "data_ml": "🤖 Data / ML / AI",
    "firmware": "💾 Firmware / Embedded",
    "other": "🧩 Other",
}


def is_faang(company: str, terms: list[str]) -> bool:
    """Token-based match so 'apple' hits 'Apple Inc' but not 'Snapple'."""
    tokens = set(re.findall(r"[a-z0-9]+", (company or "").lower()))
    return any(t in tokens for t in terms)


def faang_jobs(jobs: list[Job], terms: list[str]) -> list[Job]:
    terms = [t.lower() for t in (terms or [])]
    if not terms:
        return []
    return [j for j in jobs if is_faang(j.company, terms)]


def group_by_category(jobs: list[Job], order: list[str]) -> list[tuple[str, list[Job]]]:
    buckets: dict[str, list[Job]] = {}
    for j in jobs:
        buckets.setdefault(j.category or "other", []).append(j)
    ordered_keys = [c for c in order if c in buckets]
    ordered_keys += [c for c in buckets if c not in order]
    return [(c, buckets[c]) for c in ordered_keys]


def _counts_summary(grouped: list[tuple[str, list[Job]]]) -> str:
    parts = []
    for cat, jobs in grouped:
        label = _CATEGORY_LABELS.get(cat, cat).split(" ", 1)[-1]
        parts.append(f"{len(jobs)} {label}")
    return ", ".join(parts)


def build_subject(jobs: list[Job], grouped, prefix: str, faang: list[Job] | None = None) -> str:
    if faang:
        names = ", ".join(sorted({j.company for j in faang}))
        return f"🚨 FAANG job out now — {names} ({len(jobs)} new internship(s))"
    return f"{prefix} {len(jobs)} new internship(s) — {_counts_summary(grouped)}"


def _faang_banner(faang: list[Job]) -> str:
    items = []
    for j in sorted(faang, key=lambda x: (x.company.lower(), x.title.lower())):
        loc = escape(j.location_str) if j.location_str else ""
        items.append(
            "<li style='margin:4px 0'>"
            f"<a href='{escape(j.url)}' style='color:#b91c1c;font-weight:700;"
            f"text-decoration:none'>{escape(j.title)}</a>"
            f"<span style='color:#7f1d1d'> — {escape(j.company)}</span>"
            + (f"<span style='color:#999;font-size:12px'> · {loc}</span>" if loc else "")
            + "</li>"
        )
    return (
        "<div style='background:#fff1f0;border:2px solid #e11d48;border-radius:8px;"
        "padding:14px 16px;margin:14px 0'>"
        "<div style='font:700 17px system-ui,sans-serif;color:#b91c1c;margin-bottom:6px'>"
        "🚨 FAANG roles just posted — apply now</div>"
        f"<ul style='margin:0;padding-left:20px;font:14px system-ui,sans-serif'>{''.join(items)}</ul>"
        "</div>"
    )


def build_html(grouped: list[tuple[str, list[Job]]], total: int, faang: list[Job] | None = None) -> str:
    headline = "🚨 FAANG job out now" if faang else "🚀 Daily Internship Digest"
    rows = []
    if faang:
        rows.append(_faang_banner(faang))
    rows.append(
        f"<p style='font:14px system-ui,sans-serif;color:#444'>"
        f"<b>{total}</b> new internship posting(s) matched your filters.</p>"
    )
    for cat, jobs in grouped:
        label = _CATEGORY_LABELS.get(cat, cat)
        rows.append(
            f"<h2 style='font:600 18px system-ui,sans-serif;color:#111;"
            f"margin:24px 0 8px;border-bottom:2px solid #eee;padding-bottom:4px'>"
            f"{escape(label)} ({len(jobs)})</h2>"
        )
        # sort by company then title for readability
        for j in sorted(jobs, key=lambda x: (x.company.lower(), x.title.lower())):
            loc = escape(j.location_str) if j.location_str else "—"
            meta_bits = [b for b in [loc, j.season, str(j.year) if j.year else None] if b]
            meta = escape(" · ".join(meta_bits))
            rows.append(
                "<div style='font:14px system-ui,sans-serif;margin:6px 0;"
                "padding:8px 10px;background:#fafafa;border-radius:6px'>"
                f"<a href='{escape(j.url)}' style='color:#1a56db;font-weight:600;"
                f"text-decoration:none'>{escape(j.title)}</a>"
                f"<span style='color:#666'> — {escape(j.company)}</span><br>"
                f"<span style='color:#888;font-size:12px'>{meta}</span>"
                "</div>"
            )
    body = "".join(rows)
    return (
        "<div style='max-width:680px;margin:0 auto'>"
        "<h1 style='font:700 22px system-ui,sans-serif;color:#111'>"
        f"{escape(headline)}</h1>"
        f"{body}"
        "<p style='font:12px system-ui,sans-serif;color:#aaa;margin-top:32px'>"
        "Generated by intern_pos_emailer. Tune sources/filters in <code>config/</code>.</p>"
        "</div>"
    )


def build_text(grouped: list[tuple[str, list[Job]]], total: int, faang: list[Job] | None = None) -> str:
    lines = []
    if faang:
        lines.append("*** FAANG JOB OUT NOW ***")
        for j in sorted(faang, key=lambda x: (x.company.lower(), x.title.lower())):
            lines.append(f"  -> {j.title} — {j.company}  {j.url}")
        lines.append("")
    lines += [f"{total} new internship posting(s):", ""]
    for cat, jobs in grouped:
        lines.append(f"== {_CATEGORY_LABELS.get(cat, cat)} ({len(jobs)}) ==")
        for j in sorted(jobs, key=lambda x: (x.company.lower(), x.title.lower())):
            loc = j.location_str or "—"
            lines.append(f"- {j.title} — {j.company} [{loc}]")
            lines.append(f"  {j.url}")
        lines.append("")
    return "\n".join(lines)


def send_email(
    jobs: list[Job],
    secrets: dict[str, str],
    email_cfg: dict,
    *,
    subject_override: str | None = None,
    html_override: str | None = None,
    text_override: str | None = None,
) -> bool:
    """Send the digest. Returns True if sent, False if skipped (missing creds)."""
    user = secrets.get("GMAIL_USER")
    password = secrets.get("GMAIL_APP_PASSWORD")
    to = secrets.get("EMAIL_TO") or user
    if not (user and password and to):
        log.warning("email skipped: GMAIL_USER / GMAIL_APP_PASSWORD / EMAIL_TO not all set")
        return False

    order = email_cfg.get("category_order", ["software", "data_ml", "firmware", "other"])
    grouped = group_by_category(jobs, order)
    faang = faang_jobs(jobs, email_cfg.get("faang_companies", []))
    subject = subject_override or build_subject(
        jobs, grouped, email_cfg.get("subject_prefix", "[Intern Alert]"), faang
    )
    html = html_override or build_html(grouped, len(jobs), faang)
    text = text_override or build_text(grouped, len(jobs), faang)

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = user
    recipients = [addr.strip() for addr in to.split(",") if addr.strip()]
    msg["To"] = ", ".join(recipients)
    msg.set_content(text)
    msg.add_alternative(html, subtype="html")

    context = ssl.create_default_context()
    try:
        with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT, context=context) as server:
            server.login(user, password)
            server.send_message(msg, from_addr=user, to_addrs=recipients)
        log.info("email sent to %s (%d jobs)", recipients, len(jobs))
        return True
    except Exception as exc:  # noqa: BLE001
        log.error("email send failed: %s", exc)
        return False
